import React, { useState, useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { motion } from 'framer-motion';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { FileText, Download, Sparkles, Crown, Loader2, CheckCircle } from 'lucide-react';
import { getAverageCycleLength, MOODS, SYMPTOMS_LIST } from '@/lib/cycleUtils';
import { format, parseISO, subDays } from 'date-fns';
import { Link } from 'react-router-dom';

export default function PDFReport() {
  const [user, setUser] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [reportType, setReportType] = useState('self');
  const [report, setReport] = useState(null);

  useEffect(() => { base44.auth.me().then(setUser); }, []);

  const { data: cycleLogs = [] } = useQuery({ queryKey: ['cycleLogs'], queryFn: () => base44.entities.CycleLog.list('-start_date', 12) });
  const { data: dailyLogs = [] } = useQuery({ queryKey: ['allDailyLogs'], queryFn: () => base44.entities.DailyLog.list('-date', 90) });

  const isPremium = user?.subscription_status === 'active';
  const avgCycle = getAverageCycleLength(cycleLogs);

  // Summarize symptoms
  const symptomCounts = {};
  dailyLogs.forEach(l => (l.symptoms || []).forEach(s => { symptomCounts[s] = (symptomCounts[s] || 0) + 1; }));
  const topSymptoms = Object.entries(symptomCounts).sort((a, b) => b[1] - a[1]).slice(0, 5)
    .map(([id, count]) => `${SYMPTOMS_LIST.find(s => s.id === id)?.label || id} (${count}x)`).join(', ');

  const moodCounts = {};
  dailyLogs.forEach(l => { if (l.mood) moodCounts[l.mood] = (moodCounts[l.mood] || 0) + 1; });
  const topMood = Object.entries(moodCounts).sort((a, b) => b[1] - a[1])[0];
  const topMoodLabel = topMood ? (MOODS.find(m => m.id === topMood[0])?.label || topMood[0]) : 'N/A';

  const generateReport = async () => {
    if (!isPremium) return;
    setGenerating(true);
    setReport(null);

    const prompt = reportType === 'doctor'
      ? `Generate a detailed, professional menstrual health report suitable for a doctor consultation. Include:
         - Patient summary (do not use real name, use "Patient")
         - Cycle analysis: average cycle length ${avgCycle} days, ${cycleLogs.length} cycles tracked
         - Most common symptoms: ${topSymptoms || 'None logged'}
         - Most common mood: ${topMoodLabel}
         - Recent cycle dates: ${cycleLogs.slice(0, 4).map(c => c.start_date).join(', ')}
         - Health observations and patterns
         - Questions to ask the doctor
         - Recommendations
         Write in clear medical note format. Include a disclaimer that this is AI-generated from a wellness app, not a clinical assessment.`
      : `Generate a warm, personal menstrual health summary report for a young woman aged 13-23. Include:
         - A friendly welcome and summary of her tracking
         - Cycle stats: average ${avgCycle} days, ${cycleLogs.length} cycles tracked
         - Top symptoms: ${topSymptoms || 'Nothing major logged — great!'}
         - Mood patterns: Most frequent mood is ${topMoodLabel}
         - Wellness insights and patterns noticed
         - Personalized self-care tips based on her data
         - Encouragement and positive affirmations
         Keep it warm, supportive, age-appropriate, and empowering. Use some emojis. End with a reminder to see a doctor if she has concerns.`;

    const content = await base44.integrations.Core.InvokeLLM({ prompt, model: 'claude_sonnet_4_6' });
    setReport({ content, generatedAt: new Date().toISOString(), type: reportType });
    setGenerating(false);
  };

  const downloadReport = () => {
    if (!report) return;
    const blob = new Blob([
      `FLOWCARE HEALTH REPORT\n${'='.repeat(40)}\nGenerated: ${format(parseISO(report.generatedAt), 'MMMM d, yyyy HH:mm')}\nType: ${report.type === 'doctor' ? 'Doctor Report' : 'Personal Report'}\n\nDISCLAIMER: This report is generated by an AI wellness app and is NOT a medical diagnosis. Always consult a qualified healthcare professional.\n${'='.repeat(40)}\n\n${report.content}`
    ], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `flowcare-report-${format(new Date(), 'yyyy-MM-dd')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!isPremium) {
    return (
      <div className="px-5 pt-12 pb-8 flex flex-col items-center text-center">
        <Crown className="w-12 h-12 text-primary mb-4" />
        <h1 className="font-heading text-xl font-bold mb-2">AI Health Reports</h1>
        <p className="text-sm text-muted-foreground mb-6 max-w-xs">
          Generate beautiful AI health reports for yourself and your doctor. Premium feature.
        </p>
        <Link to="/subscribe">
          <Button className="rounded-xl font-heading font-bold px-8">Upgrade to Premium</Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="px-5 pt-6 pb-10 space-y-5">
      <div className="flex items-center gap-3">
        <Sparkles className="w-6 h-6 text-primary" />
        <h1 className="font-heading text-2xl font-bold">AI Health Report</h1>
      </div>

      {/* Report type selector */}
      <div className="grid grid-cols-2 gap-3">
        {[
          { id: 'self', label: 'Personal Report', emoji: '💕', desc: 'Warm summary for yourself' },
          { id: 'doctor', label: 'Doctor Report', emoji: '🏥', desc: 'Clinical format for your doctor' },
        ].map(t => (
          <button
            key={t.id}
            onClick={() => setReportType(t.id)}
            className={`p-4 rounded-2xl border-2 text-left transition-all ${reportType === t.id ? 'border-primary bg-primary/5' : 'border-border bg-card'}`}
          >
            <span className="text-2xl">{t.emoji}</span>
            <p className="font-heading font-bold text-sm mt-1">{t.label}</p>
            <p className="text-xs text-muted-foreground">{t.desc}</p>
          </button>
        ))}
      </div>

      {/* Data summary */}
      <Card className="p-4 bg-secondary/30">
        <p className="text-xs font-bold text-muted-foreground uppercase tracking-wide mb-2">Report will include</p>
        <div className="grid grid-cols-2 gap-2 text-xs">
          <p>📅 {cycleLogs.length} cycles tracked</p>
          <p>📊 Avg {avgCycle}-day cycle</p>
          <p>😊 Top mood: {topMoodLabel}</p>
          <p>🩺 {Object.keys(symptomCounts).length} symptoms logged</p>
        </div>
      </Card>

      <Button
        onClick={generateReport}
        disabled={generating}
        className="w-full rounded-xl font-heading font-bold py-6 text-base"
      >
        {generating ? (
          <span className="flex items-center gap-2"><Loader2 className="w-5 h-5 animate-spin" /> Generating your report...</span>
        ) : (
          <span className="flex items-center gap-2"><Sparkles className="w-5 h-5" /> Generate {reportType === 'doctor' ? 'Doctor' : 'Personal'} Report</span>
        )}
      </Button>
      {generating && <p className="text-xs text-center text-muted-foreground">This takes about 15–20 seconds. Our AI is carefully reviewing your data 💕</p>}

      {/* Generated report */}
      {report && (
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <Card className="p-5 space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <CheckCircle className="w-5 h-5 text-green-500" />
                <p className="font-heading font-bold">Report Ready!</p>
              </div>
              <Button size="sm" onClick={downloadReport} className="rounded-xl font-heading">
                <Download className="w-3.5 h-3.5 mr-1" /> Download
              </Button>
            </div>
            <div className="bg-secondary/30 rounded-xl p-4 max-h-96 overflow-y-auto">
              <pre className="text-xs whitespace-pre-wrap font-body leading-relaxed">{report.content}</pre>
            </div>
            <p className="text-[10px] text-muted-foreground text-center">
              ⚠️ AI-generated for informational purposes only. Not a medical diagnosis.
            </p>
          </Card>
        </motion.div>
      )}
    </div>
  );
}